# Generated by Django 6.0.3 on 2026-04-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, help_text='Généré automatiquement à partir du nom si laissé vide.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la recette')),
                ('slug', models.SlugField(blank=True, help_text="Identifiant unique pour l'URL (généré automatiquement).", max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Courte description')),
                ('ingredients', models.TextField(verbose_name='Liste des ingrédients')),
                ('steps', models.TextField(verbose_name='Étapes de préparation')),
                ('prep_time', models.PositiveIntegerField(default=0, verbose_name='Temps de préparation (minutes)')),
                ('cook_time', models.PositiveIntegerField(default=0, verbose_name='Temps de cuisson (minutes)')),
                ('servings', models.PositiveIntegerField(default=4, verbose_name='Nombre de portions')),
                ('difficulty', models.CharField(choices=[('EASY', 'Facile'), ('MEDIUM', 'Moyen'), ('HARD', 'Difficile')], default='MEDIUM', max_length=10, verbose_name='Difficulté')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/images/', verbose_name='Photo du plat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipe.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['-created_at'],
            },
        ),
    ]
